server:
  port: 10000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.1.15:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.15:8848

    sentinel:
      transport:
        dashboard: 192.168.1.15:8080 #配置sentinel dashboard地址
        
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.1.15
    port: 6379
    password: tarena

  ###配置spring cache
  cache:
    type: redis
    redis:
      time-to-live: 3600000 #1小时过期，毫秒为单位
      key-prefix: cache_  #缓存key值前缀
      use-key-prefix: true
      cache-null-values: true #是否缓存空值，防止缓存穿透

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 #逻辑已删除值（默认为1）
      logic-not-delete-value: 0 #逻辑未删除值（默认为0）

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.lwhtarena.glmall: debug

