server:
  port: 40000


spring:
  application:
    name: gulimall-cart

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.15:8848

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: 192.168.1.15:8858
  ##服务追踪
  zipkin:
    base-url: 192.168.1.15:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

  redis:
    port: 6379
    host: 192.168.77.130

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true


  session:
    store-type: redis

#配置线程池
gulimall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'


