### 服务启动端口
server:
  port: 80
spring:
  application:
    name: mt-gateway
  cloud:
    gateway:
      discovery:
        locator:
#          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          lower-case-service-id: true
      routes:
        - id: weixin_routh #路由的id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址(静态)
          uri: lb://app-mt-weixin #匹配后提供服务的路由地址
          predicates:
            - Path=/get/** #断言，路径相匹配的进行路由
          filters:
            - SwaggerHanderFilter ### 指定filter
            - StripPrefix=0

        - id: member_routh #路由的id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址(静态)
          uri: lb://app-mt-weixin  #匹配后提供服务的路由地址
          predicates:
            - Path=/get/** #断言，路径相匹配的进行路由
            - After=2020-05-09T21:34:39.200+08:00[Asia/Shanghai]
              #- Cookie=username,zzyy
            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
          filters:
            - SwaggerHanderFilter ### 指定filter
            - StripPrefix=1
      x-forwarded:
        enabled: false

### 网关服务注册到eureka注册中心
eureka:
  instance:
    hostname: mt-gateway
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8100/eureka
#logging:
#  level:
#    org.springframework: cloud.gateway: debug
