server:
  port: 30000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.15:8848
    alicloud:
      access-key: LTAI4FwvfjSycd1APnuG9bjj
      secret-key: O6xaxyiWfSIitcOkSuK27ju4hXT5Hl
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-hello

  application:
    name: gulimall-third-party
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
