server:
  port: 11000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.1.15:3306/gulimall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.15:8848
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: 192.168.1.15:8848
  ##服务追踪
  zipkin:
    base-url: 192.168.1.15:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

  application:
    name: gulimall-ware

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.lwhtarena.gl: debug

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'