server:
  port: 12000

spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.15:8848

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: 192.168.1.15:8858
  ##服务追踪
  zipkin:
    base-url: 192.168.1.15:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

  redis:
    host: 192.168.1.15
    port: 6379
    password: tarena

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

  thymeleaf:
    cache: false

  session:
    store-type: redis

logging:
  level:
    com.xunqi.gulimall.search: debug
    root: warn
  pattern:
    console: "%d{yyyy-MM-dd} [%thread] - %msg%n"

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
