server:
  port: 9000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.1.15:3306/gulimall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: 192.168.1.15
    port: 5672
    virtual-host: glmall
    ##在springboot2.2.0.RELEASE版本之前是amqp正式支持的属性，用来配置消息发送到交换器之后是否触发回调方法，（spring.rabbitmq.publisher-confirm=true）
    ##在2.2.0及之后该属性过期使用spring.rabbitmq.publisher-confirm-type属性配置代替，用来配置更多的确认类型；
    ### NONE值是禁用发布确认模式，是默认值
    ### CORRELATED值是发布消息成功到交换器后会触发回调方法
    ### SIMPLE值经测试有两种效果，其一效果和CORRELATED值一样会触发回调方法，其二在发布消息成功后使用rabbitTemplate调用waitForConfirms或waitForConfirmsOrDie方法等待broker节点返回发送结果，根据返回结果来判定下一步的逻辑，要注意的点是waitForConfirmsOrDie方法如果返回false则会关闭channel，则接下来无法发送消息到broker;
    publisher-confirm-type: simple #开启发送端确认
    publisher-returns: true #开启发送端消息抵达队列的确认
    template:
      mandatory: true #只要抵达队列，以异步发送优先回调我们这个returnconfirm
    listener:
      simple:
        acknowledge-mode: manual #手动ack消息

  thymeleaf:
    cache: false
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.15:8848

  application:
    name: gulimall-order

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: 192.168.1.15:8848
  ##服务追踪
  zipkin:
    base-url: 192.168.1.15:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

  redis:
    host:


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

seata:
  application-id: glmall-order
  tx-service-group: glmall-order_tx_group
  service:
    vgroup-mapping:
      glmall-order_tx_group: default




